//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblCategory
{
    public tblCategory()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int CatID { get; set; }
    public string CatName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblCompany
{
    public tblCompany()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int CompanyID { get; set; }
    public string CompanyName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblMyTemp
{
    public int ID { get; set; }
    public int ProductID { get; set; }
    public System.DateTime DateTime { get; set; }
    public long Random { get; set; }

    public virtual tblProduct tblProduct { get; set; }
}

public partial class tblOrderDetail
{
    public int ID { get; set; }
    public int ProductID { get; set; }
    public decimal ProductPrice { get; set; }
    public int OrderID { get; set; }

    public virtual tblOrderMain tblOrderMain { get; set; }
}

public partial class tblOrderMain
{
    public tblOrderMain()
    {
        this.tblOrderDetails = new HashSet<tblOrderDetail>();
    }

    public int OrderID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }

    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
}

public partial class tblProduct
{
    public tblProduct()
    {
        this.tblMyTemps = new HashSet<tblMyTemp>();
    }

    public int ProID { get; set; }
    public string ProName { get; set; }
    public int ProQuantity { get; set; }
    public decimal ProPrice { get; set; }
    public string ProImageName { get; set; }
    public int CatID { get; set; }
    public int CompanyID { get; set; }

    public virtual tblCategory tblCategory { get; set; }
    public virtual tblCompany tblCompany { get; set; }
    public virtual ICollection<tblMyTemp> tblMyTemps { get; set; }
    public virtual tblProduct tblProduct1 { get; set; }
    public virtual tblProduct tblProduct2 { get; set; }
}

public partial class CartedProducts_Result
{
    public int ProID { get; set; }
    public string ProName { get; set; }
    public int ProQuantity { get; set; }
    public decimal ProPrice { get; set; }
    public string ProImageName { get; set; }
    public int CatID { get; set; }
    public int CompanyID { get; set; }
    public int ID { get; set; }
    public int ProductID { get; set; }
    public long Random { get; set; }
    public System.DateTime DateTime { get; set; }
}

public partial class GetCartedProducts_Result
{
    public int ProID { get; set; }
    public string ProName { get; set; }
    public int ProQuantity { get; set; }
    public decimal ProPrice { get; set; }
    public string ProImageName { get; set; }
    public int CatID { get; set; }
    public int CompanyID { get; set; }
}

public partial class GetCartedProductsList_Result
{
    public int ProID { get; set; }
    public string ProName { get; set; }
    public int ProQuantity { get; set; }
    public decimal ProPrice { get; set; }
    public string ProImageName { get; set; }
    public int CatID { get; set; }
    public int CompanyID { get; set; }
    public int ProductID { get; set; }
}

public partial class GetCategories_Result
{
    public int CatID { get; set; }
    public string CatName { get; set; }
}

public partial class GetProducts_Result
{
    public int ProID { get; set; }
    public string ProName { get; set; }
    public int ProQuantity { get; set; }
    public decimal ProPrice { get; set; }
    public string ProImageName { get; set; }
    public int CatID { get; set; }
    public int CompanyID { get; set; }
}

public partial class GetTempsData_Result
{
    public int ID { get; set; }
    public int ProductID { get; set; }
    public long Random { get; set; }
    public System.DateTime DateTime { get; set; }
}
