//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class ECommPracticeEntities : DbContext
{
    public ECommPracticeEntities()
        : base("name=ECommPracticeEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<tblCategory> tblCategories { get; set; }
    public DbSet<tblCompany> tblCompanies { get; set; }
    public DbSet<tblProduct> tblProducts { get; set; }
    public DbSet<tblMyTemp> tblMyTemps { get; set; }
    public DbSet<tblOrderDetail> tblOrderDetails { get; set; }
    public DbSet<tblOrderMain> tblOrderMains { get; set; }

    public virtual ObjectResult<GetCategories_Result> GetCategories()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategories_Result>("GetCategories");
    }

    public virtual ObjectResult<GetProducts_Result> GetProducts(Nullable<int> categoryId)
    {
        var categoryIdParameter = categoryId.HasValue ?
            new ObjectParameter("CategoryId", categoryId) :
            new ObjectParameter("CategoryId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts", categoryIdParameter);
    }

    public virtual ObjectResult<GetTempsData_Result> GetTempsData(Nullable<long> random)
    {
        var randomParameter = random.HasValue ?
            new ObjectParameter("random", random) :
            new ObjectParameter("random", typeof(long));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTempsData_Result>("GetTempsData", randomParameter);
    }

    public virtual ObjectResult<GetCartedProducts_Result> GetCartedProducts(Nullable<int> productId)
    {
        var productIdParameter = productId.HasValue ?
            new ObjectParameter("productId", productId) :
            new ObjectParameter("productId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartedProducts_Result>("GetCartedProducts", productIdParameter);
    }

    public virtual ObjectResult<GetCartedProductsList_Result> GetCartedProductsList(Nullable<int> productId)
    {
        var productIdParameter = productId.HasValue ?
            new ObjectParameter("productId", productId) :
            new ObjectParameter("productId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartedProductsList_Result>("GetCartedProductsList", productIdParameter);
    }

    public virtual ObjectResult<CartedProducts_Result> CartedProducts(Nullable<long> uniqueId)
    {
        var uniqueIdParameter = uniqueId.HasValue ?
            new ObjectParameter("uniqueId", uniqueId) :
            new ObjectParameter("uniqueId", typeof(long));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CartedProducts_Result>("CartedProducts", uniqueIdParameter);
    }
}
